import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
// Used in FadeInSection
import "./globals.css";
import Navigator from "./components/header";
import Footer from "./components/footer";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

// Noto Sans KR 폰트 설정
const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "700"], // 필요한 굵기 추가
});


export const metadata: Metadata = {
  title: "pageFactory",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/2FD.svg",
  }
};

// Dashboard layout
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={notoSansKR.className} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var saved=localStorage.getItem('theme');var dark=saved?saved==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.classList.toggle('dark',dark);document.documentElement.style.colorScheme=dark?'dark':'light'}catch(e){}})()`,
          }}
        />
      </head>
      <body>
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <header>
            <Navigator />
        </header>
        <main>{children}</main>
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
