import type { Metadata } from "next";
import localFont from "next/font/local";
// Used in FadeInSection
import "./globals.css";
import Navigator from "./components/header";
import Footer from "./components/footer";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

const pretendard = localFont({
  src: [
    { path: "./fonts/woff2/Pretendard-Thin.woff2", weight: "100", style: "normal" },
    { path: "./fonts/woff2/Pretendard-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "./fonts/woff2/Pretendard-Light.woff2", weight: "300", style: "normal" },
    { path: "./fonts/woff2/Pretendard-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/woff2/Pretendard-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/woff2/Pretendard-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/woff2/Pretendard-Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/woff2/Pretendard-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "./fonts/woff2/Pretendard-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-pretendard",
  display: "swap",
  fallback: ["system-ui", "-apple-system", "Segoe UI", "sans-serif"],
});


export const metadata: Metadata = {
  title: "pageFactory",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/2FD.svg",
  }
};

// Dashboard layout
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={pretendard.variable} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var saved=localStorage.getItem('theme');var dark=saved?saved==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.classList.toggle('dark',dark);document.documentElement.style.colorScheme=dark?'dark':'light'}catch(e){}})()`,
          }}
        />
      </head>
      <body>
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <header>
            <Navigator />
        </header>
        <main>{children}</main>
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
