import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "pageFactory",
  description: "Generated by create next app",
};

// Dashboard layout
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <header>
            <Navigator />
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}

function Navigator() {
    return (
        <nav className="nav">
            <div className="left">page:Factory</div>
            <div className="right">
                <Link href="/" className="link">Home</Link>
                <Link href="/profile" className="link">Profile</Link>
                <Link href="/portfolio" className="link">Portfolio</Link>
            </div>
        </nav>
    )
}